In [1]:
#Import Data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import os
import glob
import datetime
import warnings
warnings.filterwarnings("ignore")
import prophet #will try some time series

In [4]:
df = pd.read_csv('data/EPL_stats_since03.csv')

In [5]:
df.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,WinningTeam
0,08/16/2003,Arsenal,Everton,2,1,H,1,0,H,M Halsey,...,7,8,15,6,9,1,3,1,1,Arsenal
1,08/16/2003,Birmingham,Tottenham,1,0,H,1,0,H,R Styles,...,7,20,27,1,4,3,5,0,0,Birmingham
2,08/16/2003,Blackburn,Wolves,5,1,H,2,0,H,J Winter,...,5,8,14,6,2,1,1,0,0,Blackburn
3,08/16/2003,Fulham,Middlesbrough,3,2,H,1,1,D,G Poll,...,5,18,16,7,6,1,1,0,0,Fulham
4,08/16/2003,Leicester,Southampton,2,2,D,2,0,H,M Riley,...,10,27,15,2,7,3,1,0,0,Draw